### ISSUE TITLE
[Suggest] 님들 TDD 적용 어떠신가요?

### ISSUE THREAD

**Issue by DongWooE** [ESC-CoM/esc-server#16]
## 🙋🏻‍♂️ 제안 사항
저희가 어제 객체지향 스터디에서 TDD 관련 맛보기를 해봤는데 저희가 나중에 운영단계에서 벌어질 수 있는 문제들을
미리 대비할 수 있겠다고 생각했어요 그래서 저희 플젝에 TDD 적용하시는건 어떠신가요?
TDD 방법은 각자 조사해서 종합 후 어떤 식으로 진행할지 정할 예정입니다

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

@youngjaeee @dsjinwongo

**Comment by youngjaeee** [comment]
그래서 저희 플젝에 TDD 적용하시는건 어떠신가요?
-> 저도 TDD 적용 좋은 것 같습니다!

**Comment by DongWooE** [comment]
TDD를 적용하기 전에 생각보다 이것저것 공부할게 많아 보이고
일단 기능 개발을 우선적으로 들어가는 것이 맞다고 판단이 드네요
그래서 TDD 개발은 나중에 다시 한번 이야기해보면 좋을 것 같네요
