### ISSUE TITLE
[Share] 소개팅/과팅 보드 ui 입니다~

### ISSUE THREAD

**Issue by DongWooE** [ESC-CoM/esc-server#20]
## 🙋🏻‍♂️ 공유 사항
공유할 내용을 적어주세요.

@youngjaeee  영재님
클라이언트단에서 현재 개발하고 있는 ui 예요
이미지에는 여자 1명도 과팅을 만들 수 있지만
저건 단순히 mock 데이터라 실제로는 클라에서 1명이면 소개팅으로 한다고 하시네요

![image](https://user-images.githubusercontent.com/63181439/161608878-5a6ca87e-3abf-4a2a-a4e2-5a16fce29e6d.png)

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by youngjaeee** [comment]
확인했습니다! 추가적으로 질문사항 생기면 다시 남기겠습니다~
