### ISSUE TITLE
[Feat] LocationDistrict 설계

### ISSUE THREAD

**Issue by jsween5723** [ESC-CoM/esc-server#33]
## 💡 개요
행정구역 권역을 담당하는 엔티티를 설계합니다.

## 🤩 기능 설명
[KIKmix.20190701.xlsx](https://github.com/ESC-CoM/esc-server/files/12000855/KIKmix.20190701.xlsx)
해당 엑셀파일을 서비스의 요구사항에 맞게 정제하기 위한 엔티티를 설계합니다.

### 자료
도_(특별,광역)시, (일반)시_군_구, 읍_면_동

### 고려사항
초기 안: 도, 시, 군_구
읍면동 제외

### 생긴 예외
세종시는 군_구가 없다.
광역시 특별시 등은 도에 포함이 안된다.

- [ ] 세종시만 읍면동을 추가할 것인지
- [ ] 다른 곳도 읍면동을 추가할 것인지
- [x] 세종시는 세부 분할 없이 모두 세종특별자치시로 구성할 것인지

코멘트 남겨주세요.

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by EunjiShin** [comment]
아 어렵네요..
그냥 모든 데이터에 대해 동리명까지 관리할까요? (시도명, 시군구명, 읍면동명, 동리명까지)
제일 최소 단위가 동리명인 것 같아서 학교 위치 등을 관리할때도 이쪽이 더 확장 가능성이 높지 않을까 싶어요..!

<img width="633" alt="스크린샷 2023-07-10 오후 8 10 26" src="https://github.com/ESC-CoM/esc-server/assets/38103085/bbf69436-46ca-4e5f-b2a6-c4e76387d832">

세종시 소재 대학교 위치는 위와 같이 표시되고 있네요

**Comment by juyeong-s** [comment]
엇 저는 제가 살고있는 곳도 군구가 없어서 읍면동까지 추가하는 걸로 생각하고 있었어요..!

**Comment by jsween5723** [comment]
지난 번 기획 때 구까지 한다는 이야기가 나와서요! 
한 번 의견을 맞춰봐야 할 것 같습니다.

**Comment by kingyong9169** [comment]
음 읍면동 단위까지 가면 너무 복잡하기도 하고 해당 단위까지 소속된 학교들이 많지 않을 것 같아서요.

도, 시, 군구 단위까지 해도 충분하지 않을까라는 생각이긴 합니다! 디자이너, pm 분들의 의견도 함께 들어봐요!

**Comment by jsween5723** [comment]
@kingyong9169 
위에 선택지에서 3번째신거죠?

**Comment by EunjiShin** [comment]
온라인 미팅에서 시도 / 시군구까지만 관리하기로 결정됨!
