### ISSUE TITLE
[Feat] 학교 데이터 지역 연결

### ISSUE THREAD

**Issue by jsween5723** [ESC-CoM/esc-server#57]
## 💡 개요
CSV를 파싱할 때 지역 FK를 추가합니다.

## 🍒 세부 기능
CSV의 주소를 가지고 Location District의 FK를 매칭하는 로직을 추가합니다.

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by EunjiShin** [comment]
[전국대학및전문대학정보표준데이터.csv](https://github.com/ESC-CoM/esc-server/files/12144750/default.csv)
