### ISSUE TITLE
[Bug][ESC-25] GET /api/v1/majors NPE

### ISSUE THREAD

**Issue by jsween5723** [ESC-CoM/esc-server#83]
## ❌ 버그 발생
```bash
ed: java.lang.NullPointerException: Cannot invoke "com.esc.bluespring.domain.university.entity.University.getUniversityName()" because the return value of "com.esc.bluespring.domain.major.entity.Major.getUniversity()" is null] with root cause

java.lang.NullPointerException: Cannot invoke "com.esc.bluespring.domain.university.entity.University.getUniversityName()" because the return value of "com.esc.bluespring.domain.major.entity.Major.getUniversity()" is null
```
아래 데이터들 처럼 학과 데이터에 학교 이름이 정확히 일치하지 않아 대학과의 관계가 없는 경우가 포함되면 NPE가 발생합니다.
지금은 삭제하여 괜찮지만 혹시 모르니 재업로드 후 확인 부탁드립니다.
학과는 학교가 무조건 있어야 하는 관계이니 Entity에 Nullable false 체크 부탁드립니다!
또한 학과 조회 시 대학의 pk도 포함하는 것이 좋을 것 같습니다. (추후 어드민페이지에서 하이퍼링크등으로 활용) 
혹시 아래처럼 사용하면 어떨까요?
```json
    {
        "id": 43439,
         "university" : {
             "id": 123,
            "name": "오산대학교",
             "campus": "본교",
         },
        "majorName": "드론융합부사관과",
        "createdTimestamp": 1691242977,
        "updatedTimestamp": 1691242977
    },
```

<img width="922" alt="스크린샷 2023-08-07 오전 10 06 50" src="https://github.com/ESC-CoM/esc-server/assets/136432473/1c309bc4-e4c3-491b-a2b8-aa7db8ba9b70">

## 🐞 발생한 위치
버그가 발생한 위치를 알려주세요.(Component, Page 등)

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by EunjiShin** [comment]
> 지금은 삭제하여 괜찮지만 혹시 모르니 재업로드 후 확인 부탁드립니다. 
> 학과는 학교가 무조건 있어야 하는 관계이니 Entity에 Nullable false 체크 부탁드립니다!

넵! 확인 감사합니다~ S3 작업 완료 후 바로 진행하겠습니다!

> 또한 학과 조회 시 대학의 pk도 포함하는 것이 좋을 것 같습니다. (추후 어드민페이지에서 하이퍼링크등으로 활용)

아하 학과의 소속 대학을 누르면 대학 상세 페이지로 넘어가는 등으로 활용할 수 있겠네요!
넵 그럼 위 이슈 수정하면서 GET API res도 수정해두겠습니다 👍

**Comment by jsween5723** [comment]
University N+1걸리는데 fetch join이나 앱 join 구현 부탁드립니다!
