### ISSUE TITLE
[Feat] 프로필 등록 기능 구현

### ISSUE THREAD

**Issue by jsween5723** [ESC-CoM/esc-server#85]
## 💡 개요
프로필(멤버) 도메인을 구현합니다.
휴대폰 인증을 합니다.

## 🤩 기능 설명
개발할 기능에 대해서 말씀해주세요.

## 🍒 세부 기능
어떤 세부 기능을 구현할지 말씀해주세요.
### 프로필 등록 flow
- [x] 휴대폰 인증을 한다. (필수)
  - [ ] POST /api/v1/auth/phone-code/generate로 백엔드에서 문자를 보내고 캐시에 저장한다.
    - [ ] 같은 휴대폰은 하루 5번만 가능하도록 제한한다.
  - [ ] POST /api/v1/auth/phone-code/validate로 백엔드에서 검증 후 인증 성공 여부를 캐시에 저장한다.
    - [ ] 검증 시 사용한 휴대폰 번호로 계정을 조회한다.
      - 있을 때
          세션에 profileId 추가
          isSigned=true 반환
       - 없을 때
          isSigned=false 반환

true라면 회원가입 생략 혹은 다시 생성 여부 확인
false라면 회원정보 등록을 요구하며 아래 폼 노출

### 폼
- 닉네임. 
    - [ ] GET /api/v1/member/nickname/validate (중복체크, 글자수 체크)
- 프로필 사진
- 성별을 선택한다.
- 학교를 선택한다.
  - [ ] 선택의 용이함을 위해 지역을 먼저 선택할 수 있도록 제공한다.
    - [ ] depth별로, parentId로 조회하는 기능 추가(children 조회 x)
      - GET /api/v1/location-districts/category?parentIds=1,2&depths=0,1
    - [ ] 상위 지역 선택시 하위 모든 학교가 이름 순으로 표시된다.
        - GET /api/v1/schools?locationDistrictsIds=1,2
- 학생증을 업로드한다.
- [ ] POST /api/v1/auth/join로 폼 제출
    - 검증한다.
      - 휴대폰 인증여부가 캐시에 없을 경우, reject한다.
      - 이미 가입된 번호일 경우, reject한다.
      - 닉네임이 중복된 경우, reject한다.

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by EunjiShin** [comment]
`POST /api/v1/auth/phone-code/generate`
`POST /api/v1/auth/phone-code/validate`

는 현재 존재하는데 (POST, GET의 /mobile/verification), 기구현된 API의 엔드포인트와 내부 로직을 수정하시는 것 맞을까요?
현재 해당 API의 refactor와 test 태스크가 할당되어 있어 혹시 작업 내용 겹칠까봐 여쭤봅니다~ 

++ 그리고 휴대폰 인증 제한 5번 혹시 기획단에서 결정된 내용일까요? 처음 듣는 것 같아서.. 혹시 놓친 거일까봐 질문드려요!

**Comment by jsween5723** [comment]
@EunjiShin 기존 로직 재활용 할 것 같아요
5회는 해두어야하는 게 안했을 때, 저희 과금이랑 관련돼서 횟수는 추후 조정하더라도 두는 게 맞다고 판단했습니다.
