### ISSUE TITLE
[Setting] [ESC-32] 개발용 local 프로필 분리

### ISSUE THREAD

**Issue by EunjiShin** [ESC-CoM/esc-server#86]
## 🙋🏻‍♂️ 환경 세팅

- mysql 컨테이너와 쿼리 로그를 추가한 개발용 Local 프로필을 세팅합니다.

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by jsween5723** [comment]
h2 임베디드로 하는 것이 더 가볍지 않을까요?

**Comment by EunjiShin** [comment]
@jsween5723 
맞아요! 그래서 h2 그대로 사용할까 고민하다가, RDS에 DDL 적용하기 전에 테스트 해 볼 수 있는게 편하겠다 싶어서 mysql 컨테이너를 띄웠어요.
(예를 들면 학교 테이블에 인덱스 걸어서 쿼리 튜닝되는거 보고 싶은데, 이건 직접 해보기 전에는 잘 될지 알 수 없는 거니까!)

**Comment by jsween5723** [comment]
알겠습니다! 로컬 DB에 데이터가 엄청 많지 않은 이상 풀테이블 전체 조회쿼리랑 최적화된 쿼리 비교하기는 쉽지 않을 것 같긴한데
필요하긴 할 것 같네용
