### ISSUE TITLE
[Feat] SMS 모듈의 테스트 코드 작성

### ISSUE THREAD

**Issue by EunjiShin** [ESC-CoM/esc-server#87]
## 💡 개요
이슈의 개요를 적어주세요.

## 🤩 기능 설명
개발할 기능에 대해서 말씀해주세요.

## 🍒 세부 기능
- [ ] sms 송신 서비스의 테스트 코드 추가
- [ ] 핸드폰 인증 서비스의 테스트 코드 추가

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by jsween5723** [comment]
핸드폰인증 테스트코드는 제가 겸사겸사할게요

**Comment by jsween5723** [comment]
@EunjiShin 좀 지연되는 것 같아서 제가 하겠습니다.
