### ISSUE TITLE
[Feat] [ESC-66] 신고하기 기능

### ISSUE THREAD

**Issue by EunjiShin** [ESC-CoM/esc-server#95]
## 💡 개요
신고 기능을 구현합니다.

## 🤩 기능 설명

> 230812 기준 피그마에 문의하기 기능 X => 신고만 먼저 진행합니다

## 🍒 세부 기능
어떤 세부 기능을 구현할지 말씀해주세요.
- [x] 신고하기
  - controller & service
    - [x] POST /reports : 특정 유저 신고
    - ~~[x] GET /members/reports : 특정 유저가 다른 멤버를 신고한 기록 조회~~
    - ~~[x] GET /members/reported : 특정 유저가 신고받은 기록 조회~~
    - [x] GET /reports : 모든 신고 기록 조회
    - [x] DELETE /reports/{reportId} : 특정 멤버 신고 취소
    - [x] PUT /reports/{reportId} : 특정 유저 신고 사유 수정
    - [x] 요청을 보낸 유저가 신고자인지 확인
  - entity (확인 필요)
    - [x] 신고
    - [x] 멤버 신고
    - [x] 신고 사유 수정
  - [x] 테스트 코드

## 📖 참고 사항

- n회 이상 신고 받은 유저에 대한 제재가 필요한가? (기획적으로)

**Comment by jsween5723** [comment]
POST /reports
GET /reports?reporter_ids= & target_member_ids=
으로 만드는 게 좀 더 낫지 않을까요?

**Comment by EunjiShin** [comment]
@jsween5723 

신고나 문의가 멤버 관련 신고 / 과팅 관련 신고 < 처럼 여러개로 나뉠 수 있을 것 같아서 도메인명도 추가했습니다!
ex. 멤버 신고 = /members/reports
ex. 과팅 신고 = /meetings/reports

아직 신고, 문의 관련 디자인 / 기획이 명확하지 않아서 확정은 못했는데, 엔티티도 멤버 신고, 과팅 신고, ... 로 서로 다른 테이블로 나누면 어떨까 싶어요. 어떻게 생각하시나요?

**Comment by jsween5723** [comment]
그렇다면 JSON컬럼을 이용하는 건 어떨까요?
신고라 함은 대상만 바뀔 뿐 다른 컬럼은 모두 중복된다고 생각해서
아래와 같이 활용하는 것도 나쁘지 않을 것 같다는 생각입니다.
https://romcanrom.tistory.com/195

**Comment by jsween5723** [comment]
문의 내용은 body에 컬럼으로 구분하면 되지 않나요?

**Comment by jsween5723** [comment]
GET /members/reported : 특정 유저가 신고받은 기록 조회
 GET /reports?reported={memberId} 로 바꾸는 것은 어떨까요?

**Comment by EunjiShin** [comment]
@jsween5723 

옹 의견이랑 참고자료 감사합니다! 저도 좋아요 👍
하면서도 신고 대상별로 컨트롤러가 너무 많아지는 것 같다고 생각했는데, 추상 팩토리로 구현하면 신고 타입에 대해 여러 로직을 컨트롤할 수 있어 관리가 편할 것 같네요! 한번 알려주신 내용 참고해서 구현해보겠습니다 :)
